### PR TITLE
Add a script to load firmware files

### PR DESCRIPTION
**Pull request by Meumeu**
The latest udev dropped support for loading firmware and Linux 3.4 needs a userspace helper if the firmware is not in the binary. This implements the firmware loading.

### CODE REVIEW

**Comment by crondog** [comment]
Hey thanks for doing this.

**Comment by depau** [comment]
Is this related somehow to firmware.service? Do we still need it or does this implementation do its job?

**Comment by crondog** [comment]
Firmware.service is still needed (i think i cant test right now) because nothing knows how to start wlan and it also needs to enable BT

**Comment by Meumeu** [comment]
firmware.sh only loads the firmware, the (wrongly named) firmware.service loads the wlan module, then the kernel requests the firmware using udev. In recent kernels, the firmware is directly read from the filesystem so it was removed from udev.

**Comment by depau** [comment]
Gotcha.

**Pull request merged**
